In [3]:
pip install -U ydata-profiling

Collecting ydata-profilingNote: you may need to restart the kernel to use updated packages.

  Using cached ydata_profiling-4.18.0-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (2.10.3)
Collecting PyYAML<6.1,>=6.0.3 (from ydata-profiling)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Using cached visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (2.1.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Using cached minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Using cached phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Using cached multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (0.14.4)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Using cached typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Using cached ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (1.9.4)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Using cached dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\chavd\anaconda3\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\chavd\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\chavd\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\chavd\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\chavd\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chavd\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chavd\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\chavd\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\chavd\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\chavd\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\chavd\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chavd\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chavd\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chavd\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chavd\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in c:\users\chavd\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\chavd\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Collecting typing-extensions>=4.12.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: attrs>=19.3.0 in c:\users\chavd\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (24.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\chavd\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Using cached puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\chavd\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Using cached ydata_profiling-4.18.0-py2.py3-none-any.whl (398 kB)
Using cached ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Using cached dacite-1.9.2-py3-none-any.whl (16 kB)
Using cached multimethod-1.12-py3-none-any.whl (10 kB)
Using cached phik-0.12.5-cp313-cp313-win_amd64.whl (678 kB)
Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Using cached typeguard-4.4.4-py3-none-any.whl (34 kB)
Using cached visions-0.8.1-py3-none-any.whl (105 kB)
Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Using cached minify_html-0.18.1-cp313-cp313-win_amd64.whl (3.1 MB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached puremagic-1.30-py3-none-any.whl (43 kB)
Installing collected packages: puremagic, minify-html, filetype, typing-extensions, PyYAML, multimethod, dacite, typeguard, imagehash, visions, phik, ydata-profiling

   --- ------------------------------------  1/12 [minify-html]
   ------ ---------------------------------  2/12 [filetype]
  Attempting uninstall: typing-extensions
   ------ ---------------------------------  2/12 [filetype]
    Found existing installation: typing_extensions 4.12.2
   ------ ---------------------------------  2/12 [filetype]
   ---------- -----------------------------  3/12 [typing-extensions]
    Uninstalling typing_extensions-4.12.2:
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ---------- -----------------------------  3/12 [typing-extensions]
   ---------- -----------------------------  3/12 [typing-extensions]
  Attempting uninstall: PyYAML
   ---------- -----------------------------  3/12 [typing-extensions]
    Found existing installation: PyYAML 6.0.2
   ---------- -----------------------------  3/12 [typing-extensions]
    Uninstalling PyYAML-6.0.2:
   ---------- -----------------------------  3/12 [typing-extensions]
      Successfully uninstalled PyYAML-6.0.2
   ---------- -----------------------------  3/12 [typing-extensions]
   ------------- --------------------------  4/12 [PyYAML]
   ------------- --------------------------  4/12 [PyYAML]
   ------------- --------------------------  4/12 [PyYAML]
   -------------------- -------------------  6/12 [dacite]
   ----------------------- ----------------  7/12 [typeguard]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   --------------------------------- ------ 10/12 [phik]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ---------------------------------------- 12/12 [ydata-profiling]

Successfully installed PyYAML-6.0.3 dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 typeguard-4.4.4 typing-extensions-4.15.0 visions-0.8.1 ydata-profiling-4.18.0

In [4]:
import pandas as pd
from ydata_profiling import ProfileReport

df = pd.read_csv("Housing.csv")

profile = ProfileReport(df, title="EDA Report", explorative=True)
profile.to_file("eda_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:00<00:00, 366.67it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
!pip install autoviz

Requirement already satisfied: autoviz in c:\users\chavd\anaconda3\lib\site-packages (0.1.905)
Requirement already satisfied: xlrd in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.9.4)
Requirement already satisfied: emoji in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (2.15.0)
Requirement already satisfied: pyamg in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (5.3.0)
Requirement already satisfied: scikit-learn in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (0.14.4)
Requirement already satisfied: nltk in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (0.19.0)
Requirement already satisfied: xgboost<1.7,>=0.82 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (2025.3.2)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (4.15.0)
Requirement already satisfied: pandas-dq>=1.29 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (2.1.3)
Requirement already satisfied: hvplot>=0.9.2 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (0.11.3)
Requirement already satisfied: holoviews>=1.16.0 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.20.2)
Requirement already satisfied: panel>=1.4.0 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (1.7.0)
Requirement already satisfied: pandas>=2.0 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (2.2.3)
Requirement already satisfied: matplotlib>3.7.4 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in c:\users\chavd\anaconda3\lib\site-packages (from autoviz) (0.13.2)
Requirement already satisfied: scipy in c:\users\chavd\anaconda3\lib\site-packages (from xgboost<1.7,>=0.82->autoviz) (1.15.3)
Requirement already satisfied: bokeh>=3.1 in c:\users\chavd\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.6.2)
Requirement already satisfied: colorcet in c:\users\chavd\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: packaging in c:\users\chavd\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (24.2)
Requirement already satisfied: param<3.0,>=2.0 in c:\users\chavd\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.2.0)
Requirement already satisfied: pyviz-comms>=2.1 in c:\users\chavd\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.0.2)
Requirement already satisfied: Jinja2>=2.9 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (1.3.1)
Requirement already satisfied: pillow>=7.1.0 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (11.1.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\users\chavd\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\chavd\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.2)
Requirement already satisfied: cycler>=0.10 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\chavd\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chavd\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chavd\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: bleach in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (6.2.0)
Requirement already satisfied: linkify-it-py in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.0.0)
Requirement already satisfied: markdown in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (3.8)
Requirement already satisfied: markdown-it-py in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (0.3.0)
Requirement already satisfied: requests in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.32.3)
Requirement already satisfied: tqdm in c:\users\chavd\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\chavd\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>3.7.4->autoviz) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\chavd\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\chavd\anaconda3\lib\site-packages (from scikit-learn->autoviz) (3.5.0)
Requirement already satisfied: webencodings in c:\users\chavd\anaconda3\lib\site-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in c:\users\chavd\anaconda3\lib\site-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\chavd\anaconda3\lib\site-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.0)
Requirement already satisfied: click in c:\users\chavd\anaconda3\lib\site-packages (from nltk->autoviz) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in c:\users\chavd\anaconda3\lib\site-packages (from nltk->autoviz) (2024.11.6)
Requirement already satisfied: colorama in c:\users\chavd\anaconda3\lib\site-packages (from click->nltk->autoviz) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chavd\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chavd\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chavd\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chavd\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in c:\users\chavd\anaconda3\lib\site-packages (from statsmodels->autoviz) (1.0.1)

In [5]:
from autoviz.AutoViz_Class import AutoViz_Class

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)

In [9]:
import seaborn as sns
import pandas as pd

In [10]:
df = pd.read_csv('diabetes.csv')

In [11]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [19]:
df.to_csv('diabetes.csv')

In [20]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [21]:
from autoviz.AutoViz_Class import AutoViz_Class

In [22]:
av = AutoViz_Class()

In [23]:
import matplotlib.pyplot as plt

In [26]:
filename = 'diabetes.csv'

dft = av.AutoViz(
    filename
)

Shape of your Data Set loaded: (768, 10)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  1
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    10 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0']
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Number of All Scatter Plots = 3
All Plots done
Time to run AutoViz = 4 seconds

 ###################### AUTO VISUALIZATION Completed ########################

In [27]:
from autoviz.AutoViz_Class import AutoViz_Class
import matplotlib.pyplot as plt

av = AutoViz_Class()

filename = "diabetes.csv"

df = av.AutoViz(
    filename=filename,
    sep=",",
    depVar="",          # leave empty for EDA
    dfte=None,
    header=0,
    verbose=1,
    lowess=False,
    chart_format="png",
    max_rows_analyzed=100000,
    max_cols_analyzed=30
)

Shape of your Data Set loaded: (768, 10)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  1
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    10 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0']
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Number of All Scatter Plots = 3
All Plots done
Time to run AutoViz = 4 seconds

 ###################### AUTO VISUALIZATION Completed ########################